# Generated by Django 5.0.6 on 2024-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_alter_poem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='reviews',
            field=models.ManyToManyField(null=True, related_name='poems', to='poems.review'),
        ),
    ]
