# Generated by Django 5.0.6 on 2024-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_alter_poem_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='poem',
            field=models.ManyToManyField(null=True, related_name='review', to='poems.poem'),
        ),
    ]
